name: Validate

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: devenv
      - name: Install Devenv
        run: nix profile add nixpkgs#devenv
      - name: Test the development environment
        run: devenv test
